ai_tips&enter
s1f10220227/sleep-comm-ai pull request #111
Opened 2024-12-13 03:11 UTC by s1f10220227

毎日睡眠の豆知識を送れるようにしました。リンクの後に豆知識が送られてきます。
Enterでメッセージを送れないようにしました。
また、メッセージを改行して送れるようにしました。

テスト
1. 時間を設定してリンクの後に豆知識が送られてくることを確認
2. Enterでメッセージが送れないことを確認
3. 送った時とリロードした時の両方で改行が反映されていることを確認

2024-12-13 07:21 UTC, s1F102202099 approved these changes

2024-12-13 07:22 UTC, s1F102202099 approved these changes

2024-12-15 04:28 UTC, s1f10220252 requested changes
リロードするまで改行されずに表示されるのは私だけでしょうか？

![image](https://github.com/user-attachments/assets/fa3bd884-cd5a-4d90-bfdd-03fcc090d694)
![image](https://github.com/user-attachments/assets/eefd49ed-95c0-446e-b236-3b4a68f69d7e)

2024-12-15 05:43 UTC, s1f10220227 commented
> リロードするまで改行されずに表示されるのは私だけでしょうか？

開発者モードを使ってjsが変更されているかを確認してください

2024-12-15 06:01 UTC, s1f10220227 commented
私の環境では問題なさそうでした。
ただリアルタイムに送った時とリロードした時で若干表示がかわるみたいですね。
![スクリーンショット 2024-12-15 145844](https://github.com/user-attachments/assets/2d593b9d-7921-4722-9105-1ea025d308ed)
![スクリーンショット 2024-12-15 145919](https://github.com/user-attachments/assets/bcc10456-87cd-4c97-8c0c-3d3b9a398139)
![スクリーンショット 2024-12-15 145949](https://github.com/user-attachments/assets/aee3f7e1-d154-41ba-a50b-f95af01a9b88)

2024-12-15 06:13 UTC, s1f10220252 approved these changes
![スクリーンショット 2024-12-15 150339](https://github.com/user-attachments/assets/cd7c61e6-5194-41a7-8a91-a89e513d4e63)

以前の `room.js` を読み込んでいるようだったので、
```bash
docker compose exec django python manage.py collectstatic
```
```bash
docker compose down // restartではなく
```
```bash
docker compose up --build -d
```
を実行したところ、正常に動作しました。ありがとうございます。

![スクリーンショット 2024-12-15 150836](https://github.com/user-attachments/assets/261854ff-bf3b-4e66-8301-7a36af09c5a0)

2024-12-15 06:14 UTC, s1f10220252 commented
> ただリアルタイムに送った時とリロードした時で若干表示がかわるみたいですね。

気にするほどの変化ではなさそうです。

2024-12-15 15:07 UTC, s1f102200233 approved these changes
指定した時間に睡眠のtipsが送られてくることが確認できました。また、enterでメッセージが送信されず、改行がメッセージに反映されることが確認できました。ありがとうございます。
即時表示とリロード後の表示でフォーマットが異なる問題については、このブランチに対する以下のプルリクエストで修正できているはずです。
#122

2024-12-18 03:11 UTC, s1f10220256 approved these changes
確認できました。改行できるようにしていただいたおかげでめちゃ見やすいです！

2024-12-18 04:58 UTC, merged