Feature/add flow line to answers on the home screen
s1f10220227/sleep-comm-ai pull request #77
Opened 2024-10-16 08:00 UTC by s1f102200233

### 概要
グループ作成・参加の前にグループ参加前の質問に答えるようにしました

### 変更内容
- グループ参加前の質問に未回答の状態でグループ作成・参加をしようとすると、回答ページに遷移するようにしました。
- ホーム画面に、回答ページへのボタンを設置しました。
- 回答ページへのボタンの上に現在の回答状況を表示するようにしました。

### テスト方法
1. ホーム画面に移動する
2. 回答ページへのボタンが正しく動作することを確認
3. 回答状況が正しく表示されることを確認
4. 質問に未回答のままではグループを作成できないことを確認
5. その際に回答ページに遷移することを確認
6. 質問に未回答のままではグループに参加できないことを確認
7. その際に回答ページに遷移することを確認
8. 回答後、正しく作成・参加が行えることを確認

### 関連するIssue
- #74
- #76

2024-10-18 07:20 UTC, s1F102202099 approved these changes

2024-10-25 06:11 UTC, s1F102202099 approved these changes

2024-10-30 05:57 UTC, s1F102202099 approved these changes

2024-11-10 04:31 UTC, s1f10220227 requested changes
回答ページには行けたのですがDBに保存できないのでFalseのままです。

![スクリーンショット 2024-11-10 132651](https://github.com/user-attachments/assets/36317bff-584d-49e6-a46a-13182532f96f)

2024-11-10 05:03 UTC, s1f102200233 commented
> 回答ページには行けたのですがDBに保存できないのでFalseのままです。
> 
> ![スクリーンショット 2024-11-10 132651](https://private-user-images.githubusercontent.com/107394970/384658780-36317bff-584d-49e6-a46a-13182532f96f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTQ5ODksIm5iZiI6MTczMTIxNDY4OSwicGF0aCI6Ii8xMDczOTQ5NzAvMzg0NjU4NzgwLTM2MzE3YmZmLTU4NGQtNDllNi1hNDZhLTEzMTgyNTMyZjk2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwNDU4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2MwMTZjNWM4NjY4YWJiNjNhOGEzNDkzMzg1YmVjM2Y3ZmUwNTgxNGNiYTI2MGFjZjQwMzkzMmU0ZTUyYmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Jk050R8uro3UlC0_8cd5RzZsk3-8oIY36bJAsYRg7RI)

レビューありがとう。グループ参加前の回答が保存されるように修正しました。

2024-11-10 05:27 UTC, s1f10220227 approved these changes

2024-11-10 05:30 UTC, s1f10220227 commented
修正ありがとうございます。
回答がきちんと保存されるとTrueになり、「今日は回答済みです。」と表示できました。
またTrueの場合はグループ作成できました。

2024-11-12 01:11 UTC, s1f10220252 approved these changes
グループ加入前の質問に未回答の状態では、グループ作成・参加ができず回答ページに遷移することを確認しました。また、グループ参加前の回答も正しく保存されることも確認できました。ありがとうございます。

2024-11-22 06:04 UTC, s1F102202099 approved these changes

2024-11-27 05:38 UTC, s1f10220256 approved these changes
グループ作成、参加時に質問回答ページに偏移しました。
その後作成、回答できることを確認できました

2024-11-27 06:38 UTC, merged